FORMAT: 1A
HOST: http://scholar.aci.info/api

# ACI Scholarly Content Firehose
This API provides a Firehose to access content as it is processed by the *ACI Scholarly Blog Index*. The publishers that are approved for ACI are editorially selected as authoritative in their research field.

## Authentication
Authentication is handled by providing an API Key with every request. Each request may contain either an **api_key** URL parameter, or an **X-API-Key** HTTP Header.
API Keys may be requested by visiting http://scholar.aci.info/firehose

# Group Abstract

Abstracts are the base object for ACI. An Abstract contains the following parameters:

|Name        |Type         |Description                                                           |
|------------|-------------|----------------------------------------------------------------------|
|id          |`String`     |The unique ID for this Abstract                                       |
|type        |`String`     |For Abstracts, this will always be "Abstract"                         |
|title       |`String`     |The title (or headline) for this Abstract                             |
|excerpt     |`String`     |A brief excerpt of the summary for this Abstract                      |
|date        |`String`     |The date of publication for this article, in UTC ISO Format           |
|link        |`String`     |The link to this record in ACI, for use with citations or sharing     |
|pub         |`Publication`|The Publication record this Abstract belongs to                       |

# Group Publication

Publications belong to Abstracts. Every Abstract has exactly one Publication, and Publications have multiple Abstracts.


|Name        |Type         |Description                                                           |
|------------|-------------|----------------------------------------------------------------------|
|id          |`String`     |The unique ID for this Publication                                    |
|type        |`String`     |For Publications, this will always be "Publication"                   |
|name        |`String`     |The display name for this Publication                                 |
|lc_classes  |`List`       |A List of strings of LC Class Codes: <https://www.loc.gov/catdir/cpso/lcco/>|


# Group API

## Firehose [/firehose{?api_key,lc_class}]

Anyone can connect to the ACI Firehose with a free API key, however the free version of the API has a limited amount of metadata. If you are interested in more metadata for your experiments, please contact us.

You may connect to this API using a basic HTTP request from your favorite programming language, however we’ve also provided a Node.js client library which you may use to ingest content.

You must provide your API key either with an “X-API-Key” header, or the “api_key” URL parameter.

Please do not connect to the firehose with multiple connections. Excessive abuse of the firehose API will result in your Email Address, IP address, and API Key being blocked.

The Firehose API returns a single JSON object per line, but may also return an empty line to help keep the TCP connection alive.
You should verify the line is not empty before trying to parse a JSON object.

Abstracts are the base object for ACI. An Abstract contains the following parameters:

|Name        |Type         |Description                                                           |
|------------|-------------|----------------------------------------------------------------------|
|id          |`String`     |The unique ID for this Abstract                                       |
|type        |`String`     |For Abstracts, this will always be "Abstract"                         |
|title       |`String`     |The title (or headline) for this Abstract                             |
|excerpt     |`String`     |A brief excerpt of the summary for this Abstract                      |
|date        |`String`     |The date of publication for this article, in UTC ISO Format           |
|link        |`String`     |The link to this record in ACI, for use with citations or sharing     |
|pub         |`Publication`|The Publication record this Abstract belongs to                       |


### Search Abstracts [GET]
+ Parameters
    + api_key (required, string, `12345-6790-10223467-223478`) ... String Your API Key emailed to you after signing up at http://scholar.aci.info/firehose 
    + lc_class (optional, string, `T`) ... String LC Class to limit the Abstracts to.
   
+ Response 200 (application/json)

    + Body
    
            {
                "id": "1490f95d74f308f0195/154c4597f3d00100002",
                "type": "Abstract",
                "title": "Petrobras (PBR) Issues First International Bond in a Year",
                "date": "2016-05-18T14:07:00.000Z",
                "pub": {
                    "id": "1490f95d74f308f0195",
                    "type": "Publication",
                    "name": "Zacks Investment Research",
                    "lc_classes": [
                        "HG"
                    ]
                },
                "excerpt": "Brazil's state-run energy giant Petroleo Brasileiro S.A., or Petrobras (PBR - Analyst Report) – having the highest debt load in the oil industry – is issuing new global debts to buy back notes that will mature in the coming years. Notably, this the first time in a year that Petrobras is offering an international bond. The bond offering – likely to close by May 23, 2016 – is also the first time by any player in Brazil since June.  \n\nThe bond offering – likely to close by May 23, 2016 – is also",
                "link": "http://scholar.aci.info/view/1490f95d74f308f0195/154c4597f3d00100002"
            }