FORMAT: 1A
HOST: http://scholar.aci.info/api

# ACI Developer API
The ACI Developer API Allows anyone to integrate ACI Search results and information into a custom application, widget, or website.
While we strongly encorage developers to build amazing applications with our API, ACI reserves the right to block, or require payment for applications
which use a large amount of requests. Use of our API is goverend by our Terms and Conditions http://aci.info/terms-of-use

Unless otherwise agreed upon, in writing, by ACI Information Group, use of this API is strictly non-commercial.

Make something cool? Send us a link to support@aci.info!

Questions? Visit our support portal at http://support.aci.info.

## ACI Scholarly Content Firehose
This API provides a Firehose to access content as it is processed by the *ACI Scholarly Blog Index*. The publishers that are approved for ACI are editorially selected as authoritative in their research field.

The ACI Firehose project is currently in development and is not yet available. To be notified when it becomes available, please sign up at:

https://aci-info.formstack.com/forms/firehose_notification_list



## User-Agent Header
All Requests, no matter which API is used, require a User-Agent header. This header should contain information about your application, a version number, and an email address of a technical contact. Example:
    
    User-Agent: Console/1.0 support@aci.info
    

## Authentication
Authentication is handled by providing an API Key with every request. Each request may contain either an **api_key** URL parameter, or an **X-API-Key** HTTP Header.
API Keys may be requested by visiting http://scholar.aci.info/firehose


    

# Group Abstract

Abstracts are the base object for ACI. An Abstract contains the following parameters:

|Name        |Type         |Description                                                           |
|------------|-------------|----------------------------------------------------------------------|
|id          |`String`     |The unique ID for this Abstract                                       |
|type        |`String`     |For Abstracts, this will always be "Abstract"                         |
|title       |`String`     |The title (or headline) for this Abstract                             |
|excerpt     |`String`     |A brief excerpt of the summary for this Abstract                      |
|date        |`String`     |The date of publication for this article, in UTC ISO Format           |
|link        |`String`     |The link to this record in ACI, for use with citations or sharing     |
|pub         |`Publication`|The Publication record this Abstract belongs to                       |

# Group Publication

Publications belong to Abstracts. Every Abstract has exactly one Publication, and Publications have multiple Abstracts.


|Name        |Type         |Description                                                           |
|------------|-------------|----------------------------------------------------------------------|
|id          |`String`     |The unique ID for this Publication                                    |
|type        |`String`     |For Publications, this will always be "Publication"                   |
|name        |`String`     |The display name for this Publication                                 |
|lc_classes  |`List`       |A List of strings of LC Class Codes: <https://www.loc.gov/catdir/cpso/lcco/>|


# Group API

## Stories [/stories{?q,filters}]

The search API does not require API authentication, however only limitted data will be available.

### Search Stories [GET]
+ Parameters
    + q (required, string, `healtcare`) ... String A search string to search the full-text of each document 
    + filters (optional, string, `authors.degrees.title:PhD`) ... String An optional filter to apply, such as the example which limits to authors with a PhD. Any filter you see in a search is also available in the API. Some filters may require authentication.
   
+ Response 200 (application/json)

    + Body
    
            {
                "hits": [
                    {
                        "title": "My Project - By James Kusena",
                        "image_url": "https://67.media.tumblr.com/1a5f7aa6649c28acd632a30bb6f41a4b/tumblr_inline_of79gt0WWu1sue702_540.png",
                        "products": ["aci"],
                        "full_text": 0,
                        "date": "2016-10-18T10:00:55.000Z",
                        "pub": {
                            "$id": "14c1ee56651000e0009",
                            "$type": "Publication",
                            "name": "Healthcare Engineering & Regenerative Therapies Blog",
                            "content_type": "Abstract"
                        },
                        "authors": [
                            {
                                "$type": "Author",
                                "$id": "14c1ee564f3000e0009",
                                "name": "Elizabeth Ratcliffe",
                                "first_name": "Elizabeth",
                                "last_name": "Ratcliffe",
                                "degrees": [
                                    {
                                        "title": "PhD",
                                        "institution": {
                                            "$type": "Institution",
                                            "$id": "1472aa870286f500193",
                                            "name": "University of Nottingham"
                                        }
                                    },
                                    {
                                        "title": "MSc",
                                        "subject": "Molecular Medical Microbiology",
                                        "institution": {
                                            "$type": "Institution",
                                            "$id": "1472aa870286f500193",
                                            "name": "University of Nottingham"
                                        }
                                    },
                                ],
                                "positions": [
                                    {
                                        "institution": {
                                            "$type": "Institution",
                                            "$id": "14876aadd0f6f920132",
                                            "name": "Loughborough University"
                                        },
                                    "title": "Postdoctoral Research Scientist",
                                    "group": "EPSRC Centre for Innovative Manufacturing in Regenerative Medicine"
                                    }
                                ]
                            }
                        ],
                        "view_url": "http://scholar.aci.info/view/14c1ee56651000e0009/157d88b08920001a517bce0",
                        "$id": "14c1ee56651000e0009/157d88b08920001a517bce0",
                        "$type": "Story"
                    }
                ]
            }

## Firehose [/firehose{?api_key,lc_class}]

Anyone can connect to the ACI Firehose with a free API key, however the free version of the API has a limited amount of metadata. If you are interested in more metadata for your experiments, please contact us.

You may connect to this API using a basic HTTP request from your favorite programming language, however we’ve also provided a Node.js client library which you may use to ingest content.

You must provide your API key either with an “X-API-Key” header, or the “api_key” URL parameter.

Please do not connect to the firehose with multiple connections. Excessive abuse of the firehose API will result in your Email Address, IP address, and API Key being blocked.

The Firehose API returns a single JSON object per line, but may also return an empty line to help keep the TCP connection alive.
You should verify the line is not empty before trying to parse a JSON object. The Firehose returns either an `Abstract` or an `INFO` object on each line.

`INFO` objects may be ignored for the purposes of processing data.


### Stream Firehose [GET]
+ Parameters
    + api_key (required, string, `12345-6790-10223467-223478`) ... String Your API Key emailed to you after signing up at http://scholar.aci.info/firehose 
    + lc_class (optional, string, `T`) ... String LC Class to limit the Abstracts to.
   
+ Response 200 (application/json)

    + Body
    
            {
                "id": "1490f95d74f308f0195/154c4597f3d00100002",
                "type": "Abstract",
                "title": "Petrobras (PBR) Issues First International Bond in a Year",
                "date": "2016-05-18T14:07:00.000Z",
                "pub": {
                    "id": "1490f95d74f308f0195",
                    "type": "Publication",
                    "name": "Zacks Investment Research",
                    "lc_classes": [
                        "HG"
                    ]
                },
                "excerpt": "Brazil's state-run energy giant Petroleo Brasileiro S.A., or Petrobras (PBR - Analyst Report) – having the highest debt load in the oil industry – is issuing new global debts to buy back notes that will mature in the coming years. Notably, this the first time in a year that Petrobras is offering an international bond. The bond offering – likely to close by May 23, 2016 – is also the first time by any player in Brazil since June.  \n\nThe bond offering – likely to close by May 23, 2016 – is also",
                "link": "http://scholar.aci.info/view/1490f95d74f308f0195/154c4597f3d00100002"
            }